// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0DukmnJfLdtGC1btFZlr_TwzJ_aWcbNk',
    appId: '1:791799780250:web:c9dc08cb3230c989062023',
    messagingSenderId: '791799780250',
    projectId: 'fir-flutter-codelab-as',
    authDomain: 'fir-flutter-codelab-as.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-as.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA16VsAkAmbj_RSz3axhx7SKiXWhaWxiOk',
    appId: '1:791799780250:android:3279d666c978ff60062023',
    messagingSenderId: '791799780250',
    projectId: 'fir-flutter-codelab-as',
    storageBucket: 'fir-flutter-codelab-as.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbRdl5oXm-HP9lHxMkzF6dwCohlJAfdMg',
    appId: '1:791799780250:ios:b9a6e758ef643fed062023',
    messagingSenderId: '791799780250',
    projectId: 'fir-flutter-codelab-as',
    storageBucket: 'fir-flutter-codelab-as.appspot.com',
    iosClientId: '791799780250-17b43stesghflknd31tp68c2etd6adv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbRdl5oXm-HP9lHxMkzF6dwCohlJAfdMg',
    appId: '1:791799780250:ios:b9a6e758ef643fed062023',
    messagingSenderId: '791799780250',
    projectId: 'fir-flutter-codelab-as',
    storageBucket: 'fir-flutter-codelab-as.appspot.com',
    iosClientId: '791799780250-17b43stesghflknd31tp68c2etd6adv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
