// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7-hBZCclHs6dY94bPNsR-ex9Gl9Q1js',
    appId: '1:715191378226:web:3d8e5bddc5afbf662b372b',
    messagingSenderId: '715191378226',
    projectId: 'pard-159e3',
    authDomain: 'pard-159e3.firebaseapp.com',
    storageBucket: 'pard-159e3.appspot.com',
    measurementId: 'G-TQGWK2G9T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHCuekWgj_atwrDbVcEXIx78lri0dTap0',
    appId: '1:715191378226:android:851f4f5d69bb12872b372b',
    messagingSenderId: '715191378226',
    projectId: 'pard-159e3',
    storageBucket: 'pard-159e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFCh7MDlf6ZcO-pzoj6NH1jB_vjxGOGpY',
    appId: '1:715191378226:ios:25504f702b2b44002b372b',
    messagingSenderId: '715191378226',
    projectId: 'pard-159e3',
    storageBucket: 'pard-159e3.appspot.com',
    iosClientId: '715191378226-4ls2r058v7molus45tvkuqtffl8dsucp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFCh7MDlf6ZcO-pzoj6NH1jB_vjxGOGpY',
    appId: '1:715191378226:ios:25504f702b2b44002b372b',
    messagingSenderId: '715191378226',
    projectId: 'pard-159e3',
    storageBucket: 'pard-159e3.appspot.com',
    iosClientId: '715191378226-4ls2r058v7molus45tvkuqtffl8dsucp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );
}
